### ISSUE TITLE
Неточность на карте Кичик-Алая

### ISSUE THREAD

**Issue by ArsenyN** [slazav/map_hr#2]
Увидел что обновились карты Азии, пошел смотреть и увидел неточность на карте Кичик-Алая
https://nakarte.me/#m=13/39.74615/72.50164&l=Otm/Q&nktl=D7nkt6Ij9Xf7Jya3xPYfEg
![image](https://github.com/user-attachments/assets/5ec00be0-dd7f-41e8-8442-857c5b5a95ef)
В этом месте нет хребта, там просто ригель в долине подпирающий озеро. Был там в прошлом году.

**Comment by slazav** [comment]
Спасибо большое за замечание! Исправил. Если найдете какие-то еще проблемы - пишите.
